on:
  workflow_dispatch:
  push:
    branches:
      - kernel-6.1-lts
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: pwd
        shell: bash
      - name: Build Arch Linux kernel package
        uses: Menci/build-archlinux-package@beta-v1
        with:
          platform: linux/arm64
          pkgbuild-directory: /home/runner/work/linux-aarch64-lts/linux-aarch64-lts
          target-directory: /home/runner/work/linux-aarch64-lts/linux-aarch64-lts
