on:
  workflow_dispatch:
  push:
    branches:
      - kernel-6.1-lts
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Arch Linux Package
        uses: Menci/build-archlinux-package@beta-v1
        with:
          platform: linux/arm64
          # The directory containing PKGBUILD and other files required.
          pkgbuild-directory: ${PWD}
          target-directory: ${PWD}
