on:
  workflow_dispatch:
  push:
    branches:
      - kernel-6.1-lts
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: Checkout PKGBUILD
        uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: archarm_latest
          githubToken: ${{ github.token }}
          run: |
            uname -a
            id
      - name: Check if Git tag exists
        run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
      - name: Get release version
        run: echo "::set-output name=version::$(echo $env.HEAD_TAG)"
        if: env.HEAD_TAG != ''
        id: version
      - name: Create new release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
