on:
  workflow_dispatch:
  push:
    branches:
      - kernel-6.1-lts
    tags:
      - 'v*'

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v4
      - run: ls -lah