on:
  workflow_dispatch:
  push:
    branches:
      - kernel-6.1-lts
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: archarm_latest
          githubToken: ${{ github.token }}
          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          install: |
            useradd -m -g users -G wheel user
            su -l user
            sudo pacman -Syu
            sudo pacman -S git base-devel
            git clone https://aur.archlinux.org/paru-bin
            cd paru-bin
            makepkg -si
          run: |
            uname -a
            id
            ls -lah /artifacts/
